CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,

    username VARCHAR(50) UNIQUE NOT NULL,

    password_hash TEXT NOT NULL,

    rating INTEGER NOT NULL DEFAULT 1200,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);