FROM ubuntu:24.04

RUN apt update && apt install -y \
    build-essential \
    cmake \
    libopencv-dev \
    libpqxx-dev \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

COPY . .

RUN cmake -S . -B build && cmake --build build

CMD ["./build/KungFuChessClient"]